### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by randyesq** [stevenaldinger/k8s-gogs#1]
Does this code have a license for commercial use?

**Comment by stevenaldinger** [comment]
Hey! I didn't expect anyone to even end up looking at this repo so didn't license it. I'm not sure I'd recommend it at-is since it was just a side project a couple years ago but I'd be happy to help resolve a few of the issues with it if you plan on using something derived from it commercially.
You can email me at stevenaldinger <at> gmail (avoiding robots!) if you'd like. I'll put a license on it now so you're free to do whatever you'd like though.

**Comment by stevenaldinger** [comment]
You're good to go! I added the MIT license which is a very "free" license, you're clear to do whatever you'd like with this now! Thanks for taking a look at my repos, I'm glad they're able to help you in some way.

**Comment by randyesq** [comment]
Thanks @stevenaldinger . I am not sure if we will do anything with it, but I need to answer the license question for legal before I even start! Thanks for the quick response.
